### ISSUE TITLE
Can't get history / query current side

### ISSUE THREAD

**Issue by dten** [DI-GROUP/TimeFlip.Docs#1]
Hey thanks for posting the docs.

So far I've managed to:

- [x] Connect
- [x] Read name (0x2a26)
- [x] Write name (0x2a26)
- [x] Read battery (0x2a19)
- [x] Read firmware version (0x2A26)
- [x] Write password (0xf1196f57) ("000000")
- [x] Read command (0xf1196f54)
- [x] Write command (0xf1196f54)
- [x] Read calibration (0xf1196f56)
- [x] Write calibration (0xf1196f56)
- [x] Sub to facets (0xf1196f52)
- [x] Read facet from notification (0xf1196f52)
- [ ] Read facet **not** from notification (0xf1196f52)
- [ ] Read command results (0xf1196f53)
- [ ] Read new data from accelerometer  (0xf1196f51)

As you can see I have most of it down, except the most important bit! Both facet and command result always return a 0 length buffer. I thought it was the password (which was new to me thanks for the docs) but I seem to be entering that correctly because it lets me change the device name iff it has been entered.

The command I am trying to get the history is writing `[0x01]` to `0xf1196f54` i have also tried writing the same but padded to 21 bytes since that is what the docs say the write size is but it wasn't necessary for changing the name so I don't think that's it. I also tried writing `[0x10]` to get the status

the accelerometer always returns the same values also

Any pointers appreciated, thanks

**Comment by lamest** [comment]
the accelerometer can freeze his values if the device is in "lock" mode.  In this mode the device is not reading accelerometer values and not updating characteristic value. 
History must have at least one interval at any time and is always consists of at least three packets 21 bytes length each. In order to read history, you need to write `0x01` to `0xf1196f54` and then read out history bits from `0xF1196F53`.

**Comment by dten** [comment]
Hi @lamest. Do you have this working? What you've described matches what I wrote. I have written to the command feature and then attempt to read from the command result feature but always receive a 0 length result

**Comment by lamest** [comment]
yep. there are services and characteristics in BLE. 
service id="F1196F50-71A4-11E6-BDF4-0800200C9A66" 
command input characteristic id="F1196F54-71A4-11E6-BDF4-0800200C9A66" 
and command output characteristic id="F1196F53-71A4-11E6-BDF4-0800200C9A66"
show your code.

**Comment by lamest** [comment]
also you can "break" timeflip device state by touching the plate with wet fingers which may lead to unconnactable device. Try using it with some cover/case.

**Comment by dten** [comment]
Sorry, I've been too busy to tidy my code enough to post lol
