### ISSUE TITLE
iOS issue scanning for a service

### ISSUE THREAD

**Issue by Terekness** [DI-GROUP/TimeFlip.Docs#2]
Hello there

I've been progressing in trying to establish a connection between my iOS device and a Timeflip cube.

My current code looks like this:

```
class ViewController: UIViewController, CBCentralManagerDelegate, CBPeripheralDelegate {
    
    let deviceInformation = CBUUID(string: "0x180A")
    
    var centralManager: CBCentralManager?
    
    var timeflipCube: CBPeripheral?

    override func viewDidLoad() {
        super.viewDidLoad()
        
        centralManager = CBCentralManager(delegate: self, queue: nil)
    }

    func centralManagerDidUpdateState(_ central: CBCentralManager) {
        switch central.state {
        case .unknown:
            print("central.state is .unknown")
        case .resetting:
            print("central.state is .resetting")
        case .unsupported:
            print("central.state is .unsupported")
        case .unauthorized:
            print("central.state is .unauthorized")
        case .poweredOff:
            print("central.state is .poweredOff")
        case .poweredOn:
            print("central.state is .poweredOn")
            centralManager?.scanForPeripherals(withServices: [deviceInformation])
        }
    }
    
    func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String : Any], rssi RSSI: NSNumber) {
        print(peripheral)
    }

    func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral) {
        print(peripheral.discoverServices([deviceInformation]))
    }
    
    func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let services = peripheral.services else { return }
        
        for service in services {
            print(service)
        }
    }
}
```

As you can see, I use the function scanForPeripherals where I specify the device information service UUID. Because I do this, my didDiscover peripheral is never called, as in it doesn't find any peripherals with that service.

This is weird, because if I specify "nil" in scanForPeripherals, it actually finds the cube (and every single other peripheral in my area).

Do you happen to see something I'm doing wrong?

EDIT: If it's intentional that the cube isn't actively broadcasting the services, and we are supposed to be going through all services in all peripherals, the cube won't be able to be used by an app in the background, since Apple requires you to specify what services you're scanning for, for that to work.
Also, in that regard, how are we supposed to identify that a peripheral is a timeflip cube? By default the cube peripheral doesn't have a name (until you rename it from your app). One would have to identify the cube by the UUID, but is the UUID unique in each cube? Am I missing something?

**Comment by lamest** [comment]
It's intentional. I'm aware of that problem on iOS. That can change in upcoming Timeflip versions. By now you can identify TF device by manufacturer specific data field. It contains ASCII string "TFv3.1" prepended by FF manufacturer code. Actually, I don't work on that anymore so wait for an official response or mail to them

**Comment by Terekness** [comment]
> It's intentional. I'm aware of that problem on iOS. That can change in upcoming Timeflip versions. By now you can identify TF device by manufacturer specific data field. It contains ASCII string "TFv3.1" prepended by FF manufacturer code. Actually, I don't work on that anymore so wait for an official response or mail to them
